### ISSUE TITLE
Missing file for tests

### ISSUE THREAD

**Issue by nim65s** [stack-of-tasks/sot-tools#15]
Hi,

@olivier-stasse : could you provide the "test.posture" file for this :

https://github.com/stack-of-tasks/sot-tools/blob/b8469a1af851ebdc8f17a8b14fd76321951c680a/tests/test_simpleseqplay.cc#L14

This is currently failing with:
```
unknown location(0): fatal error: in "BOOST_TEST_MODULE/test_simpleseqplay": std::runtime_error: Failed to open file test.posture
…/sot-tools/tests/test_simpleseqplay.cc(10): last checkpoint: "test_simpleseqplay" test entry
```

**Comment by olivier-stasse** [comment]
Done:
https://github.com/stack-of-tasks/sot-tools/blob/cmake-export/tests/test.posture
Thanks for taking care of this.
