### ISSUE TITLE
Oscillator missing in python bindings

### ISSUE THREAD

**Issue by nim65s** [stack-of-tasks/sot-tools#17]
As reported by @MaximilienNaveau, 

```python
>>> from dynamic_graph.sot.tools.oscillator import Oscillator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named oscillator
```

**Comment by MaximilienNaveau** [comment]
Tu be precise the structure of the installed folder is like this:
```
.
├── __init__.py
├── __init__.pyc
├── __init__.pyo
├── quaternion.py
├── quaternion.pyc
├── quaternion.pyo
├── se3.py
├── se3.pyc
├── se3.pyo
└── wrap.so
```
And the `__init__.py` being empty, we cannot have an easy access to the entities.

**Comment by olivier-stasse** [comment]
The CMakeLists.txt is a bit weird it does not compile the C++ plugins

**Comment by jmirabel** [comment]
from dynamic_graph.sot.tools.wrap import Oscillator

**Comment by jmirabel** [comment]
I don't think it is necessary to put each entity in a separate plugin.

**Comment by olivier-stasse** [comment]
If we could avoid to have wrap inside the python code, I think it would be better

**Comment by jmirabel** [comment]
Having one plugin for each entity is a pain in Python (one import per entity) and I don't see any benefits for them being split into multiple plugins.

With #18, you will have on *wrap.so* for each plugin. I am not sure what you don't like with `wrap`. Is it the name ?

**Comment by olivier-stasse** [comment]
I found wrap confusing. And between wrap and oscillator in terms of length, I do not see any difference.
But I agree that having a module gathering everything would be easier. 
I am afraid this is the price to pay to make the python modules relocatable.

**Comment by jmirabel** [comment]
> I am afraid this is the price to pay to make the python modules relocatable.

No, that is not true.

With the current `wrap`, you can do
`from ....wrap import Entity1, Entity2` and not
```
from ....entity1 import Entity1
from ....entity2 import Entity2
```

The term `wrap` can be renamed. The names I can think of are
- entities
- tools

Another better packaging would be:
- to remove completely `quaternion` and `se3` in favor of what is in pinocchio,
- and to install a library in `dynamic_graph/sot/tools.so` so that you can do `from dynamic_graph.sot.tools import Entity1, Entity2`.

**Comment by olivier-stasse** [comment]
I see several points in your answer:
 * Putting the plugins in one library: yes for useful plugins this completely make sense to have them in one library. And this woud simplify its usage as you have shown.
 * My main argument about wrap is the name. IMHO we should be against using it.
 * For the tools package I think that it should go inside sot-core unless there is a strong dependency we want to avoid. This would avoid to have to manage one supplementary package. Plus the name tools means that usually we do not how to classify it (I read a comment about this in ros_control and found it illuminating). The same applies to the sot-core directory. It is just adding confusion. We should more meaningful names.

And thanks for your arguments they push us in the right direction.

**Comment by jmirabel** [comment]
> * 
> 
> * My main argument about wrap is the name. IMHO we should be against using it.

So solving this issue is just a matter of renaming `wrap` and not splitting it into several pieces.

**Comment by olivier-stasse** [comment]
I would put all the c++ code in a directory called tools-for-trajectories inside sot-core and call the library tools-for-trajectories.

**Comment by nim65s** [comment]
@jmirabel : would you agree in putting all the entities from this package into a sot-core//tools-for-trajectories plugin ? And also, how would this interact with your work on boost python ?

This issue was originally for @MaximilienNaveau ; but your indication to use `from dynamic_graph.sot.tools.wrap import Oscillator` should fix his issue. Therefore, I think we can close my PR, and take our time to discuss how to properly review the whole packaging of this sot-tools project.

**Comment by MaximilienNaveau** [comment]
I will check the import using the wrap directly

**Comment by MaximilienNaveau** [comment]
> I would put all the c++ code in a directory called tools-for-trajectories inside sot-core and call the library tools-for-trajectories.

What about trajectory_generation ?
This way you get rid of the "tools"
WDYT?

**Comment by MaximilienNaveau** [comment]
`from dynamic_graph.sot.tools.wrap import Oscillator`
this does not seem to work.
I suspected it is because I am not using the https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/dynamic_graph/submodule/__init__.py.cmake ?

**Comment by olivier-stasse** [comment]
> What about the name `trajectory_generation` ?
Sounds good, but I will let @nim65s decide if it should be trajectory_generation or trajectory-generation.
I think our standard are set for the latter.

> This way you get rid of the "tools"
> WDYT?

**Comment by jmirabel** [comment]
> @jmirabel : would you agree in putting all the entities from this package into a sot-core//tools-for-trajectories plugin ? And also, how would this interact with your work on boost python ?

I am fine with moving those entities to sot-core.

**Comment by MaximilienNaveau** [comment]
Should I try to set a PR in sot-core?

**Comment by nim65s** [comment]
That would be really nice, yes :)
As you already are a user of this Osciallator, maybe you could complete my dumb unit test a bit with things that are testing actual functionalities ?
